### ISSUE TITLE
The error is this? -> Couldn't load shared library 'libsdl-arcarm64.so'

### ISSUE THREAD

**Issue by church-basement** [azureblue/MindustryPi#10]
problem with the newest [6.0 Build 126.2](https://github.com/azureblue/MindustryPi/releases/tag/v126.2)
using...
- rasberry pi 4, 4gb
- rabberry pi os bookworm
probably my bad :P
```
elliot@raspberrypi:~/games/java $ ls
libsdl-arcarm64.so  MindustryPi.jar  mindustry.sh
elliot@raspberrypi:~/games/java $ java -jar MindustryPi.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:315)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:44)
Caused by: java.lang.ExceptionInInitializerError: Exception arc.util.ArcRuntimeException: Couldn't load shared library 'libsdl-arcarm64.so' for target: Linux, 64-bit [in thread "main"]
	at arc.util.SharedLibraryLoader.load(SharedLibraryLoader.java:85)
	at arc.backend.sdl.jni.SDL.<clinit>(SDL.java:148)
	at arc.backend.sdl.SdlApplication.lambda$init$0(SdlApplication.java:73)
	at arc.backend.sdl.SdlApplication.check(SdlApplication.java:181)
	at arc.backend.sdl.SdlApplication.init(SdlApplication.java:73)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:29)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
elliot@raspberrypi:~/games/java $ 
```
huh, wonder what it's doing
`openjdk-17-jre`, `libopenal1` and `libsdl2-2.0-0` are installed.
what do you mean by proper 'proper gpu_mem setting (tested with 128mb)'?
i set gpu_mem=128 in the config.txt?

**Comment by TheLinuxSeal** [comment]
This error also happened to me
