### ISSUE TITLE
Unable to initialize SDL backend even though SDL is installed.

### ISSUE THREAD

**Issue by RainMa22** [azureblue/MindustryPi#6]
Hello, I really do appreciate the work you have put into this project. However, some issues occurred when I tried to run this program. 
The Exception is as follow:
<code>
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
        at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:315)
        at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:176)
        at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:176)
        at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:44)
</code>

I have already installed `libsdl2-2.0-0`, the SDL2 package available on the Raspi Bullseye repo.

My Device is **Raspberry Pi 3 B(1GB)**
My OS is **Raspberry Pi OS Bullseye 64bit**

Thanks in advance.

**Comment by azureblue** [comment]
Will look at it. Is that all that was printed? Can you try to run it with java -verbose:jni?

**Comment by RainMa22** [comment]
Yes, that's all the messages, typing 
```
java -jar MindustryPi.jar -verbose:jni
```
Gives the same result as well.

**Comment by RainMa22** [comment]
I tried downgrading the jre from `openjdk17-jre` to `openjdk11-jre`, the problem still persisted.

**Comment by Spyro24** [comment]
I have a problem with sdl

Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:312)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:175)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:175)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:45)

Can you please solve the problem?

**Comment by PhilAOE** [comment]
I have the same Problem.
Packages and Configurations are all successfully done.

Tried with Version 108, 110 and 126

```
java -jar Mindustry110.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:314)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:175)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:175)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:45)
```

Here some Infos in case you need it.
<details> 
  <summary>CPU</summary>
   <p>

cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 180.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 180.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 180.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 180.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03114
Serial		: 10000000b67f3dcd
Model		: Raspberry Pi 4 Model B Rev 1.4</p> 
</details>


<details> 
  <summary>System</summary>
   <p>
Linux version 5.15.61-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1579 SMP Fri Aug 26 11:13:03 BST 2022
   </p> 
</details>


<details> 
  <summary>hostnamectl</summary>
   <p>

   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: 1c4b9f5b76c84647aac079992a4abXX0
           Boot ID: c5f0f74d401a4215a874b92a06947XX6
  Operating System: Raspbian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.15.61-v7l+
      Architecture: arm
   </p> 
</details>

<details> 
  <summary>cat /etc/os-release</summary>
   <p>

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
   </p> 
</details>

**Comment by pawutan** [comment]
Hello,
I have the same problem

Tried Version 126
can't install "sudo apt install libsdl2-2.0" but  install "sudo apt install libsdl2-2.0-0" instead
I have a Raspberry Pi 400 with bullseye installed.

**Comment by lutz-fechner** [comment]
Same happens with the new bookworm based Raspberry OS.
