### ISSUE TITLE
Archlinux ARM support

### ISSUE THREAD

**Issue by tigercoding56** [azureblue/MindustryPi#8]
i use arch btw  (im waiting for the btw cpu architecture )  on a  raspberry pi

**Comment by tigercoding56** [comment]
currently this happens   `Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class arc.backend.sdl.jni.SDL
	at mindustry.desktop.DesktopLauncher.message(DesktopLauncher.java:315)
	at mindustry.desktop.DesktopLauncher.lambda$handleCrash$8(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.handleCrash(DesktopLauncher.java:176)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:44)
`

**Comment by s3rvant** [comment]
I am seeing this error as well on a Pinebook Pro running Ubuntu 20.04
